BOT_TOKEN = "7121773838:AAHhoFDNIUQwaiNBrUFPPxaxqoBKk8TZ5RA"

# EXAMPLE: BOT_TOKEN = "5953961340:AAFiBeDXt7Yb10ShbV2O5z2oCzVTgjEK43g"

START_PIC = "https://i.ibb.co/MZNzjsP/file-90.jpg"

# ENTER LINK OF PIC !

# FOR GETTING LINK, GO TO @Spl_Levi_Ackerman_Bot, SEND PIC AND REPLY /telegraph

SUPPORT_CHAT = "@OriginalSrijan"

# ENTER USERNAME OF SUPPORT GROUP OR CHANNEL WITHOUT @

if SUPPORT_CHAT[0] == "@":
    SUPPORT_CHAT = SUPPORT_CHAT[1:]
